/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>

#ifndef _Included_com_coocaa_remotectrlservice_JniUtils
#define _Included_com_coocaa_remotectrlservice_JniUtils

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     Java_com_coocaa_remotectrlservice_JniUtils_nativeSetContext
 * Method:    nativeSetContext
 * Signature: (Landroid/content/Context;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_coocaa_remotectrlservice_JniUtils_nativeSetContext
        (JNIEnv* env, jclass thiz, jobject context, jstring pkgname);

/*
 * Class:     com_coocaa_homeshell_jni_CoocaaHomeJni
 * Method:    nativeCleanup
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_coocaa_remotectrlservice_JniUtils_startCoocaaOsVnc
	(JNIEnv* env, jclass thiz, jstring pushID, jstring serverIp, jboolean accept);


bool execJCommand(std::string cmd, std::string param2, std::string param3);
std::string execJCommandR(std::string cmd, std::string param2, std::string param3);

#ifdef __cplusplus
}
#endif

#endif
